# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8910b5dd85be6d6e3aaf896eb8ce9bc56aea465e40f17cfab0720a344720e0298f0924f813f9ffd0bd7db3a32815e236dc6c18649f1610baafdcb9ac4f3cdb18

test:
  secret_key_base: 03a7c386d3f7aa0dd2247881997bcd1046a78f1e7f3f7827eaa2adda57dc5a612938c01a603e3fa5928c0186e8bb4ff2ad001da251bab7b5d5b5e089695e182f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
